# EXCEPTION ERRORS

x = 2
y = "6"

print(x + int(y)) # exception
print(str(x) + y) # exception
